name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Go
        uses: actions/setup-go@v4

      - name: Build
        run: go build

